version: '3.8'

services:
  # Main web application
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web-runner
    container_name: suitpax-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  # Dashboard application
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      target: dashboard-runner
    container_name: suitpax-dashboard
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=http://localhost:3001
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: suitpax-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: suitpax-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
      - dashboard
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: suitpax-network